#!/bin/sh
# build_apk.sh - 编译并签名连锁棋 APK
# 用法: ./build_apk.sh [--native] <keystore_password>
# 例如: ./build_apk.sh chainchess
#       ./build_apk.sh --native chainchess   # 使用 target-cpu=native 极致优化

set -e

# ── 配置 ──────────────────────────────────────────────────
KEYSTORE="release.keystore"
PRODUCT="连锁棋"
VERSION="3.1.0-beta"
OUTPUT="release/${PRODUCT}-${VERSION}.apk"
UNSIGNED_APK="tauri/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"

CARGO_CONFIG="tauri/src-tauri/.cargo/config.toml"
RUST_DIR="tauri/src-tauri"

# ── 参数解析 ──────────────────────────────────────────────
NATIVE=false
case "$1" in
  --native)
    NATIVE=true
    shift
    ;;
esac

if [ $# -lt 1 ]; then
  echo "用法: $0 [--native] <keystore_password>"
  echo "例如: $0 chainchess"
  echo "       $0 --native chainchess"
  exit 1
fi
PASSWORD="$1"

if [ ! -f "$KEYSTORE" ]; then
  echo "❌ 错误: 找不到 keystore 文件 $KEYSTORE"
  exit 1
fi

START_EPOCH=$(date +%s)

# ── 原生优化模式 ──────────────────────────────────────────
if [ "$NATIVE" = true ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  🚀 启用 native 极致优化 (target-cpu=native)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  # 创建 .cargo 目录（如果不存在）
  mkdir -p "$(dirname "$CARGO_CONFIG")"

  # 写入优化配置
  # 注：Tauri 的 android build 会自动设置 NDK 链接器路径，
  # 我们只需注入 rustflags，让 Tauri 管理整个编译流程
  cat > "$CARGO_CONFIG" << 'CONFIG_EOF'
# Auto-generated by build_apk.sh --native
# target-cpu=native: 使用本机 CPU 全部指令集优化
[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=native"]
CONFIG_EOF

  echo "  已创建: $CARGO_CONFIG"
  echo ""

  # 注册清理函数：退出时删除配置（即使中途失败）
  cleanup_native() {
    if [ -f "$CARGO_CONFIG" ]; then
      rm -f "$CARGO_CONFIG"
      echo ""
      echo "  🧹 已清理: $CARGO_CONFIG"
    fi
  }
  trap cleanup_native EXIT

  echo "  Tauri 将使用 NDK 链接器自动编译 Rust 库（带 native 优化）"
  echo ""
fi

# ── 检查 Android 项目结构 ──────────────────────────────
ANDROID_MAIN_ACTIVITY="tauri/src-tauri/gen/android/app/src/main/java/com/ywnh1/chainchess/MainActivity.kt"
if [ ! -f "$ANDROID_MAIN_ACTIVITY" ]; then
  echo "  ⚠️  Android 项目结构不匹配，正在重新初始化..."
  echo "  (若因 tauri.conf.json identifier 变更导致)"
  echo ""
  rm -rf tauri/src-tauri/gen/android
  cd tauri && npx tauri android init && cd ..
  echo "  ✅ Android 项目已重新初始化"
  echo ""
fi

# 确保 tauri.properties 存在
TAURI_PROPERTIES="tauri/src-tauri/gen/android/app/tauri.properties"
if [ -f "$TAURI_PROPERTIES" ]; then
  # 更新版本号
  sed -i "s/^tauri.android.versionName=.*/tauri.android.versionName=${VERSION%-beta}/" "$TAURI_PROPERTIES"
  # versionCode: 3.1.0 → 3001000 (major*1e6 + minor*1e3 + patch)
  VC_MAJOR=$(echo "$VERSION" | cut -d. -f1)
  VC_MINOR=$(echo "$VERSION" | cut -d. -f2)
  VC_PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d- -f1)
  VC=$(( VC_MAJOR * 1000000 + VC_MINOR * 1000 + VC_PATCH ))
  sed -i "s/^tauri.android.versionCode=.*/tauri.android.versionCode=${VC}/" "$TAURI_PROPERTIES"
fi

# ── 步骤 1: 编译 APK ─────────────────────────────────────
# TAURI_ANDROID_SKIP_RUST_BUILD 让 Gradle 跳过 Rust 重编译
# native 模式：Rust 已在上一步编译好，此处只走打包
# 普通模式：让 tauri 自行处理 Rust 编译
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔨 编译 arm64 APK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  产物: ${OUTPUT}"
echo ""

if [ "$NATIVE" != true ]; then
  export TAURI_ANDROID_SKIP_RUST_BUILD=1
fi

cd tauri
npx tauri android build --target aarch64 --apk
cd ..

# ── 步骤 2: 签名 ──────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📝 签名 APK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  keystore: ${KEYSTORE}"
echo ""

if [ ! -f "$UNSIGNED_APK" ]; then
  echo "❌ 错误: 编译产物不存在: $UNSIGNED_APK"
  echo "  编译阶段可能失败，请检查上方日志。"
  exit 1
fi

mkdir -p release
cp "$UNSIGNED_APK" "$OUTPUT"
apksigner sign --ks "$KEYSTORE" --ks-pass "pass:${PASSWORD}" --out "$OUTPUT" "$OUTPUT"

# ── 步骤 3: 验证签名 ──────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 验证签名"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

apksigner verify --verbose "$OUTPUT" | sed 's/^/  /'

# ── 完成 ──────────────────────────────────────────────────
ELAPSED=$(( $(date +%s) - START_EPOCH ))
FILESIZE=$(ls -lh "$OUTPUT" | awk '{print $5}')

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎉 构建完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  文件: ${OUTPUT}"
echo "  大小: ${FILESIZE}"
  echo "  耗时: ${ELAPSED}s"
echo ""

# 尝试复制到 Android 设备（仅当路径存在时）
if [ -d "/storage/emulated/0/用户" ]; then
  cp release /storage/emulated/0/用户/ -r
  echo "  📱 已复制到 /storage/emulated/0/用户/"
fi

echo ""
