#!/bin/sh
# build_apk.sh - 编译并签名连锁棋 APK
# 用法: ./build_apk.sh [--native] <keystore_password>
# 例如: ./build_apk.sh chainchess
#       ./build_apk.sh --native chainchess   # 使用 target-cpu=native 极致优化

set -e

# ── 配置 ──────────────────────────────────────────────────
KEYSTORE="release.keystore"
PRODUCT="连锁棋"
VERSION="3.1.5"
OUTPUT="release/${PRODUCT}-${VERSION}.apk"
UNSIGNED_APK="tauri/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"

CARGO_CONFIG="tauri/src-tauri/.cargo/config.toml"
RUST_DIR="tauri/src-tauri"

# ── 环境检测 ──────────────────────────────────────────
if [ -z "${ANDROID_HOME}" ] && [ -d "$HOME/Android/Sdk" ]; then
  export ANDROID_HOME="$HOME/Android/Sdk"
  echo "  📋 ANDROID_HOME 自动设为: $ANDROID_HOME"
fi

# ── 参数解析 ──────────────────────────────────────────────
NATIVE=false
case "$1" in
  --native)
    NATIVE=true
    shift
    ;;
esac

if [ $# -lt 1 ]; then
  echo "用法: $0 [--native] <keystore_password>"
  echo "例如: $0 chainchess"
  echo "       $0 --native chainchess"
  exit 1
fi
PASSWORD="$1"

if [ ! -f "$KEYSTORE" ]; then
  echo "❌ 错误: 找不到 keystore 文件 $KEYSTORE"
  exit 1
fi

START_EPOCH=$(date +%s)

# ── 原生优化模式 ──────────────────────────────────────────
if [ "$NATIVE" = true ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  🚀 启用 native 极致优化 (target-cpu=native)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  # 创建 .cargo 目录（如果不存在）
  mkdir -p "$(dirname "$CARGO_CONFIG")"

  # 写入优化配置
  # 注：Tauri 的 android build 会自动设置 NDK 链接器路径，
  # 我们只需注入 rustflags，让 Tauri 管理整个编译流程
  cat > "$CARGO_CONFIG" << 'CONFIG_EOF'
# Auto-generated by build_apk.sh --native
# target-cpu=native: 使用本机 CPU 全部指令集优化
[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=native"]
CONFIG_EOF

  echo "  已创建: $CARGO_CONFIG"
  echo ""

  # 清理将在统一的 cleanup_all 中处理

  echo "  Tauri 将使用 NDK 链接器自动编译 Rust 库（带 native 优化）"
  echo ""
fi

# ── 自动清理 ──────────────────────────────────────────────
# 统一退出清理：恢复被修改的配置文件
APP_BUILD_GRADLE="tauri/src-tauri/gen/android/app/build.gradle.kts"
cleanup_all() {
  # 恢复 Gradle 编译配置（JDK 21 降级）
  if [ -f "${APP_BUILD_GRADLE}.bak" ]; then
    cp "${APP_BUILD_GRADLE}.bak" "$APP_BUILD_GRADLE"
    rm -f "${APP_BUILD_GRADLE}.bak"
    echo ""
    echo "  🧹 已恢复: app/build.gradle.kts"
  fi
  # 清理 native 优化配置（--native 模式生成）
  if [ -f "$CARGO_CONFIG" ]; then
    rm -f "$CARGO_CONFIG"
    echo ""
    echo "  🧹 已清理: .cargo/config.toml"
  fi
}
trap cleanup_all EXIT

# ── Android SDK 版本检测与自动降级 ──────────────────────
# build-tools 34 无法加载 android-35+ 的平台资源
# 检测 compileSdk 是否超出 build-tools 兼容范围，是则自动降级到 34
COMPILE_SDK=$(grep 'compileSdk =' "$APP_BUILD_GRADLE" | sed 's/.*compileSdk = \([0-9]*\).*/\1/')
TARGET_SDK=$(grep 'targetSdk =' "$APP_BUILD_GRADLE" | sed 's/.*targetSdk = \([0-9]*\).*/\1/')
SDK_DOWNGRADED=false

if [ -n "$COMPILE_SDK" ]; then
  # 用 aapt2 验证平台 jar 是否可加载
  PLATFORM_JAR="${ANDROID_HOME}/platforms/android-${COMPILE_SDK}/android.jar"
  AAPT2=$(ls ${ANDROID_HOME}/build-tools/*/aapt2 2>/dev/null | head -1)
  PLATFORM_BAD=false

  if [ ! -f "$PLATFORM_JAR" ] || [ ! -s "$PLATFORM_JAR" ]; then
    PLATFORM_BAD=true
  elif [ -n "$AAPT2" ]; then
    # aapt2 dump resources 验证 jar 可被正确解析
    if ! "$AAPT2" dump resources "$PLATFORM_JAR" > /dev/null 2>&1; then
      PLATFORM_BAD=true
    fi
  fi

  if [ "$PLATFORM_BAD" = true ]; then
    echo ""
    echo "  ⚠️  Android SDK 平台 android-${COMPILE_SDK} 与当前 build-tools 不兼容"
    echo "  🛠️  自动降级 compileSdk/targetSdk: ${COMPILE_SDK} → 34"
    echo ""

    # 备份原始文件
    cp "$APP_BUILD_GRADLE" "${APP_BUILD_GRADLE}.bak"

    # 降级 compileSdk/targetSdk + 依赖版本（高版本依赖要求 compileSdk >= 35）
    awk '{
  gsub(/compileSdk = [0-9]+/, "compileSdk = 34")
  gsub(/targetSdk = [0-9]+/, "targetSdk = 34")
  gsub(/androidx\.activity:activity-ktx:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.activity:activity-ktx:1.9.3")
  gsub(/androidx\.webkit:webkit:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.webkit:webkit:1.12.1")
  gsub(/androidx\.lifecycle:lifecycle-process:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.lifecycle:lifecycle-process:2.8.7")
  print
}' "${APP_BUILD_GRADLE}.bak" > "$APP_BUILD_GRADLE"

    SDK_DOWNGRADED=true

    echo "  ✅ 已降级到 34，构建完成后自动恢复"
    echo ""
  fi
fi

# ── 检查 Android 项目结构 ──────────────────────────────
ANDROID_MAIN_ACTIVITY="tauri/src-tauri/gen/android/app/src/main/java/com/ywnh1/chainchess/MainActivity.kt"
if [ ! -f "$ANDROID_MAIN_ACTIVITY" ]; then
  echo "  ⚠️  Android 项目结构不匹配，正在重新初始化..."
  echo "  (若因 tauri.conf.json identifier 变更导致)"
  echo ""
  rm -rf tauri/src-tauri/gen/android
  (cd tauri && npx tauri android init)
  echo "  ✅ Android 项目已重新初始化"
  echo ""
fi

# 确保 tauri.properties 存在
TAURI_PROPERTIES="tauri/src-tauri/gen/android/app/tauri.properties"
if [ -f "$TAURI_PROPERTIES" ]; then
  # 更新版本号
  sed -i "s/^tauri.android.versionName=.*/tauri.android.versionName=${VERSION%-beta}/" "$TAURI_PROPERTIES"
  # versionCode: 3.1.0 → 3001000 (major*1e6 + minor*1e3 + patch)
  VC_MAJOR=$(echo "$VERSION" | cut -d. -f1)
  VC_MINOR=$(echo "$VERSION" | cut -d. -f2)
  VC_PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d- -f1)
  VC=$(( VC_MAJOR * 1000000 + VC_MINOR * 1000 + VC_PATCH ))
  sed -i "s/^tauri.android.versionCode=.*/tauri.android.versionCode=${VC}/" "$TAURI_PROPERTIES"
fi

# ── 步骤 1: 复制前端资源到 assets ──────────────────────
# Tauri CLI 在 SKIP_RUST_BUILD 下可能跳过前端资源复制
ASSETS_DIR="tauri/src-tauri/gen/android/app/src/main/assets"
FRONTEND_DIR="tauri/public"
mkdir -p "$ASSETS_DIR"
cp "$FRONTEND_DIR"/* "$ASSETS_DIR"/ 2>/dev/null
cp "tauri/src-tauri/tauri.conf.json" "$ASSETS_DIR"/ 2>/dev/null
echo "  📦 前端资源已复制到 assets ($(ls -1 "$ASSETS_DIR" | wc -l) 个文件)"

# ── 步骤 2: 编译 APK ─────────────────────────────────────
# TAURI_ANDROID_SKIP_RUST_BUILD 让 Gradle 跳过 Rust 重编译
# Tauri CLI 已负责 Rust 编译，Gradle 无需重复
export TAURI_ANDROID_SKIP_RUST_BUILD=1

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔨 编译 arm64 APK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  产物: ${OUTPUT}"
echo ""
(
  cd tauri
  npx tauri android build --target aarch64 --apk
)

# ── 步骤 2: 签名 ──────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📝 签名 APK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  keystore: ${KEYSTORE}"
echo ""

if [ ! -f "$UNSIGNED_APK" ]; then
  echo "❌ 错误: 编译产物不存在: $UNSIGNED_APK"
  echo "  编译阶段可能失败，请检查上方日志。"
  exit 1
fi

mkdir -p release
cp "$UNSIGNED_APK" "$OUTPUT"
apksigner sign --ks "$KEYSTORE" --ks-pass "pass:${PASSWORD}" --out "$OUTPUT" "$OUTPUT"

# ── 步骤 3: 验证签名 ──────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 验证签名"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

apksigner verify --verbose "$OUTPUT" | sed 's/^/  /'

# ── 完成 ──────────────────────────────────────────────────
ELAPSED=$(( $(date +%s) - START_EPOCH ))
FILESIZE=$(ls -lh "$OUTPUT" | awk '{print $5}')

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎉 构建完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  文件: ${OUTPUT}"
echo "  大小: ${FILESIZE}"
  echo "  耗时: ${ELAPSED}s"
echo ""

# 尝试复制到 Android 设备（仅当路径存在时）
if [ -d "/storage/emulated/0/用户" ]; then
  cp "$OUTPUT" /storage/emulated/0/用户/
  echo "  📱 已复制到 /storage/emulated/0/用户/"
fi

echo ""
