#!/bin/sh
# build_apk.sh - 编译并签名连锁棋 APK
# 用法: ./build_apk.sh [--release] [--native] <keystore_password>
# 例如: ./build_apk.sh chainchess              # debug 快速编译（默认）
#       ./build_apk.sh --release chainchess    # release 激进优化（性能/体积，无视编译耗时）
#       ./build_apk.sh --native chainchess     # release + target-cpu=native 极致优化
#       ./build_apk.sh --native --release chainchess

set -e

# ── 配置 ──────────────────────────────────────────────────
KEYSTORE="release.keystore"
PRODUCT="chainchess"
VERSION="3.2.2"

CARGO_CONFIG="tauri/src-tauri/.cargo/config.toml"
CARGO_TOML="tauri/src-tauri/Cargo.toml"
RUST_DIR="tauri/src-tauri"

# ── 环境检测 ──────────────────────────────────────────
if [ -z "${ANDROID_HOME}" ] && [ -d "$HOME/Android/Sdk" ]; then
  export ANDROID_HOME="$HOME/Android/Sdk"
  echo "  📋 ANDROID_HOME 自动设为: $ANDROID_HOME"
fi

# ── 参数解析 ──────────────────────────────────────────────
# --release: 启用 release 激进优化（fat LTO 等，编译慢但性能/体积最优）
# --native : target-cpu=native 极致优化，自动视为 --release
RELEASE=false
NATIVE=false
PASSWORD=""

for arg in "$@"; do
  case "$arg" in
    --release) RELEASE=true ;;
    --native) NATIVE=true ;;
    -*)
      echo "❌ 未知参数: $arg"
      echo "用法: $0 [--release] [--native] <keystore_password>"
      exit 1
      ;;
    *) PASSWORD="$arg" ;;
  esac
done

# --native 自动 release
if [ "$NATIVE" = true ]; then
  RELEASE=true
fi

if [ -z "$PASSWORD" ]; then
  echo "用法: $0 [--release] [--native] <keystore_password>"
  echo "例如: $0 chainchess"
  echo "       $0 --release chainchess"
  echo "       $0 --native chainchess"
  exit 1
fi

if [ ! -f "$KEYSTORE" ]; then
  echo "❌ 错误: 找不到 keystore 文件 $KEYSTORE"
  exit 1
fi

# ── 构建模式与产物路径 ────────────────────────────────────
if [ "$RELEASE" = true ]; then
  UNSIGNED_APK="tauri/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"
  if [ "$NATIVE" = true ]; then
    OUTPUT="release/${PRODUCT}-native-${VERSION}.apk"
  else
    OUTPUT="release/${PRODUCT}-${VERSION}.apk"
  fi
else
  # debug 快速编译产物（Tauri debug APK 已自动用 debug keystore 签名，稍后统一重签）
  UNSIGNED_APK="tauri/src-tauri/gen/android/app/build/outputs/apk/universal/debug/app-universal-debug.apk"
  OUTPUT="release/${PRODUCT}-${VERSION}-debug.apk"
fi

START_EPOCH=$(date +%s)

# ── 构建模式提示 ──────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ "$RELEASE" = true ]; then
  echo "  📦 构建模式: release（优化性能/体积，编译耗时较长）"
else
  echo "  📦 构建模式: debug（快速编译，默认）"
  echo "  包名: com.chainchess.dev（可与 release 版共存安装）"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Release 激进优化（修改 Cargo.toml，构建后自动恢复）─────
# 基础 [profile.release] 已含 opt-level=3 / strip / codegen-units=1 / panic=abort，
# --release 时再升级为 fat LTO（全程序链接优化，跨 crate 内联，
# 性能与体积更优，但链接耗时显著增加 —— 用户已声明无视编译耗时）
if [ "$RELEASE" = true ]; then
  if grep -q '^\[profile\.release\]' "$CARGO_TOML"; then
    cp "$CARGO_TOML" "${CARGO_TOML}.bak"
    if grep -q '^lto' "$CARGO_TOML"; then
      sed -i 's/^lto = .*/lto = "fat"/' "$CARGO_TOML"
    else
      sed -i '/^\[profile\.release\]/a lto = "fat"' "$CARGO_TOML"
    fi
    echo "  ⚙️  Cargo.toml: lto → fat（全程序链接优化）"
  else
    echo "  ⚠️  Cargo.toml 缺少 [profile.release]，跳过激进优化"
  fi
  echo ""
fi

# ── 原生优化模式（--native，仅 release 生效）─────────────
if [ "$NATIVE" = true ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  🚀 启用 native 极致优化 (target-cpu=native)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  # 创建 .cargo 目录（如果不存在）
  mkdir -p "$(dirname "$CARGO_CONFIG")"

  # 写入优化配置
  # 注：Tauri 的 android build 会自动设置 NDK 链接器路径，
  # 我们只需注入 rustflags，让 Tauri 管理整个编译流程
  cat > "$CARGO_CONFIG" << 'CONFIG_EOF'
# Auto-generated by build_apk.sh --native
# target-cpu=native: 使用本机 CPU 全部指令集优化
[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=native"]
CONFIG_EOF

  echo "  已创建: $CARGO_CONFIG"
  echo ""

  # 清理将在统一的 cleanup_all 中处理

  echo "  Tauri 将使用 NDK 链接器自动编译 Rust 库（带 native 优化）"
  echo ""
fi

# ── 自动清理 ──────────────────────────────────────────────
# 统一退出清理：恢复被修改的配置文件
APP_BUILD_GRADLE="tauri/src-tauri/gen/android/app/build.gradle.kts"
cleanup_all() {
  # 恢复 Gradle 编译配置（JDK 21 降级）
  if [ -f "${APP_BUILD_GRADLE}.bak" ]; then
    cp "${APP_BUILD_GRADLE}.bak" "$APP_BUILD_GRADLE"
    rm -f "${APP_BUILD_GRADLE}.bak"
    echo ""
    echo "  🧹 已恢复: app/build.gradle.kts"
  fi
  # 恢复 Cargo.toml（--release 模式修改）
  if [ -f "${CARGO_TOML}.bak" ]; then
    cp "${CARGO_TOML}.bak" "$CARGO_TOML"
    rm -f "${CARGO_TOML}.bak"
    echo ""
    echo "  🧹 已恢复: Cargo.toml"
  fi
  # 清理 update.json 修改产生的临时文件
  rm -f tmp.json
  # 清理 native 优化配置（--native 模式生成）
  if [ -f "$CARGO_CONFIG" ]; then
    rm -f "$CARGO_CONFIG"
    echo ""
    echo "  🧹 已清理: .cargo/config.toml"
  fi
}
trap cleanup_all EXIT

# ── Android SDK 版本检测与自动降级 ──────────────────────
# build-tools 34 无法加载 android-35+ 的平台资源
# 检测 compileSdk 是否超出 build-tools 兼容范围，是则自动降级到 34
COMPILE_SDK=$(grep 'compileSdk =' "$APP_BUILD_GRADLE" | sed 's/.*compileSdk = \([0-9]*\).*/\1/')
TARGET_SDK=$(grep 'targetSdk =' "$APP_BUILD_GRADLE" | sed 's/.*targetSdk = \([0-9]*\).*/\1/')
SDK_DOWNGRADED=false

if [ -n "$COMPILE_SDK" ]; then
  # 用 aapt2 验证平台 jar 是否可加载
  PLATFORM_JAR="${ANDROID_HOME}/platforms/android-${COMPILE_SDK}/android.jar"
  AAPT2=$(ls ${ANDROID_HOME}/build-tools/*/aapt2 2>/dev/null | head -1)
  PLATFORM_BAD=false

  if [ ! -f "$PLATFORM_JAR" ] || [ ! -s "$PLATFORM_JAR" ]; then
    PLATFORM_BAD=true
  elif [ -n "$AAPT2" ]; then
    # aapt2 dump resources 验证 jar 可被正确解析
    if ! "$AAPT2" dump resources "$PLATFORM_JAR" > /dev/null 2>&1; then
      PLATFORM_BAD=true
    fi
  fi

  if [ "$PLATFORM_BAD" = true ]; then
    echo ""
    echo "  ⚠️  Android SDK 平台 android-${COMPILE_SDK} 与当前 build-tools 不兼容"
    echo "  🛠️  自动降级 compileSdk/targetSdk: ${COMPILE_SDK} → 34"
    echo ""

    # 备份原始文件
    cp "$APP_BUILD_GRADLE" "${APP_BUILD_GRADLE}.bak"

    # 降级 compileSdk/targetSdk + 依赖版本（高版本依赖要求 compileSdk >= 35）
    awk '{
  gsub(/compileSdk = [0-9]+/, "compileSdk = 34")
  gsub(/targetSdk = [0-9]+/, "targetSdk = 34")
  gsub(/androidx\.activity:activity-ktx:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.activity:activity-ktx:1.9.3")
  gsub(/androidx\.webkit:webkit:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.webkit:webkit:1.12.1")
  gsub(/androidx\.lifecycle:lifecycle-process:[0-9]+\.[0-9]+\.[0-9]+/, "androidx.lifecycle:lifecycle-process:2.8.7")
  print
}' "${APP_BUILD_GRADLE}.bak" > "$APP_BUILD_GRADLE"

    SDK_DOWNGRADED=true

    echo "  ✅ 已降级到 34，构建完成后自动恢复"
    echo ""
  fi
fi

# ── 检查 Android 项目结构 ──────────────────────────────
ANDROID_MAIN_ACTIVITY="tauri/src-tauri/gen/android/app/src/main/java/com/ywnh1/chainchess/MainActivity.kt"
if [ ! -f "$ANDROID_MAIN_ACTIVITY" ]; then
  echo "  ⚠️  Android 项目结构不匹配，正在重新初始化..."
  echo "  (若因 tauri.conf.json identifier 变更导致)"
  echo ""
  rm -rf tauri/src-tauri/gen/android
  (cd tauri && npx tauri android init)
  echo "  ✅ Android 项目已重新初始化"
  echo ""
fi


# 确保 tauri.properties 存在
TAURI_PROPERTIES="tauri/src-tauri/gen/android/app/tauri.properties"
if [ -f "$TAURI_PROPERTIES" ]; then
  # 更新版本号
  sed -i "s/^tauri.android.versionName=.*/tauri.android.versionName=${VERSION%-beta}/" "$TAURI_PROPERTIES"
  # versionCode: 3.1.0 → 3001000 (major*1e6 + minor*1e3 + patch)
  VC_MAJOR=$(echo "$VERSION" | cut -d. -f1)
  VC_MINOR=$(echo "$VERSION" | cut -d. -f2)
  VC_PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d- -f1)
  VC=$(( VC_MAJOR * 1000000 + VC_MINOR * 1000 + VC_PATCH ))
  sed -i "s/^tauri.android.versionCode=.*/tauri.android.versionCode=${VC}/" "$TAURI_PROPERTIES"
fi

# ── 步骤 1: 复制前端资源到 assets ──────────────────────
# Tauri CLI 在 SKIP_RUST_BUILD 下可能跳过前端资源复制
ASSETS_DIR="tauri/src-tauri/gen/android/app/src/main/assets"
FRONTEND_DIR="tauri/public"
mkdir -p "$ASSETS_DIR"
cp -r "$FRONTEND_DIR"/. "$ASSETS_DIR"/ 2>/dev/null
cp "tauri/src-tauri/tauri.conf.json" "$ASSETS_DIR"/ 2>/dev/null
# 给 assets 里的资源引用打上版本戳，避免 WebView 缓存旧版 CSS/JS（升级后仍加载旧样式）
sed -i "s/\(href=\"style\\.css\)[^\"]*/\1?v=${VERSION}/; s/\(src=\"app\\.js\)[^\"]*/\1?v=${VERSION}/" "$ASSETS_DIR/index.html" 2>/dev/null || true
echo "  📦 前端资源已复制到 assets ($(ls -1 "$ASSETS_DIR" | wc -l) 个文件)"

# ── 步骤 2: 编译 APK ─────────────────────────────────────
# TAURI_ANDROID_SKIP_RUST_BUILD 让 Gradle 跳过 Rust 重编译
# Tauri CLI 已负责 Rust 编译，Gradle 无需重复
export TAURI_ANDROID_SKIP_RUST_BUILD=1

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ "$RELEASE" = true ]; then
  echo "  🔨 编译 arm64 release APK"
else
  echo "  🔨 编译 arm64 debug APK（快速编译）"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  产物: ${OUTPUT}"
echo ""
(
  cd tauri
  if [ "$RELEASE" = true ]; then
    npx tauri android build --target aarch64 --apk
  else
    npx tauri android build --target aarch64 --apk --debug
  fi
)

# ── 步骤 2: 签名 ──────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📝 签名 APK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  keystore: ${KEYSTORE}"
echo ""

if [ ! -f "$UNSIGNED_APK" ]; then
  echo "❌ 错误: 编译产物不存在: $UNSIGNED_APK"
  echo "  编译阶段可能失败，请检查上方日志。"
  exit 1
fi

mkdir -p release
cp "$UNSIGNED_APK" "$OUTPUT"
apksigner sign --ks "$KEYSTORE" --ks-pass "pass:${PASSWORD}" --out "$OUTPUT" "$OUTPUT"

# ── 步骤 3: 验证签名 ──────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 验证签名"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

apksigner verify --verbose "$OUTPUT" | sed 's/^/  /'

# ── 完成 ──────────────────────────────────────────────────
ELAPSED=$(( $(date +%s) - START_EPOCH ))
FILESIZE=$(ls -lh "$OUTPUT" | awk '{print $5}')
FILESIZE_BYTES=$(stat -c %s "$OUTPUT")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎉 构建完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  文件: ${OUTPUT}"
echo "  大小: ${FILESIZE}"
  echo "  耗时: ${ELAPSED}s"

# ── 步骤 4: 生成 update.json（仅 release）─────────────────
if [ "$RELEASE" = true ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  📄 验证 update.json"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  if [ -f "update.json" ]; then
    # 用 APK 真实字节数更新 .android.size（--argjson 要求合法 JSON 数值）
    jq --argjson sz "$FILESIZE_BYTES" '.platforms.android.size = $sz' update.json > tmp.json && mv tmp.json update.json

    VERSION=$(jq -r '.version' update.json)
    
    echo "  已验证: update.json"
    echo "  版本: ${VERSION}"
    echo "  尺寸: ${FILESIZE}"
    echo ""
    batcat update.json
    echo ""
    echo "  📌 上传到 Gitee Release 前请确认："
    echo "     1. update.json → 提交到 chain-chess-release 仓库 main 分支"
    echo "     2. ${OUTPUT##release/} → 上传到 Gitee Release 附件"
    echo ""
  else
    echo "update.json不存在"
  fi
else
  echo ""
  echo "  ℹ️  debug 构建，跳过 update.json 发布流程"
  echo "  💡 需要发布 APK 时请使用: $0 --release $PASSWORD"
fi

# 尝试复制到 Android 设备（仅当路径存在时）
if [ -d "/storage/emulated/0/用户" ]; then
  cp "$OUTPUT" /storage/emulated/0/用户/
  echo "  📱 已复制到 /storage/emulated/0/用户/"
  better-rm release 
fi
if [ -f "update.json" ] && [ -d "../chain-chess-release" ]; then
  cp update.json ../chain-chess-release
  echo "  🌐 已复制到 ../chain-chess-release"
  better-rm -s update.json 
fi
echo ""
