[package]
name = "chain-chess"
version = "3.2.2"
description = "连锁棋 - AI & 本地对战"
authors = ["ywnh1"]
edition = "2021"

[lib]
name = "chain_chess_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true

[dependencies]
tauri = { version = "2", features = ["custom-protocol"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rayon = "1"
rand = "0.8"
alpha_beta_pruning = "0.1.0"
tauri-plugin-opener = "2"

[target.'cfg(not(target_os = "android"))'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
semver = "1"
